export default [
  {
    firstTerm: 100,
    secondTerm: 20,
    operation: "/",
    answer: 5,
  },
  {
    firstTerm: 80,
    secondTerm: 5,
    operation: "/",
    answer: 16,
  },
  {
    firstTerm: 7,
    secondTerm: 6,
    operation: "*",
    answer: 42,
  },
  {
    firstTerm: 24,
    secondTerm: 4,
    operation: "/",
    answer: 6,
  },
  {
    firstTerm: 75,
    secondTerm: 25,
    operation: "/",
    answer: 3,
  },
  {
    firstTerm: 6,
    secondTerm: 500,
    operation: "*",
    answer: 3000,
  },
  {
    firstTerm: 200,
    secondTerm: 17,
    operation: "%->",
    answer: 34,
  },
  {
    firstTerm: 21,
    secondTerm: 21,
    operation: "*",
    answer: 441,
  },
  {
    firstTerm: 200,
    secondTerm: 18,
    operation: "%->",
    answer: 36,
  },
  {
    firstTerm: 5,
    secondTerm: 400,
    operation: "%->",
    answer: 20,
  },
  {
    firstTerm: 8,
    secondTerm: 15,
    operation: "*",
    answer: 120,
  },
  {
    firstTerm: 65,
    secondTerm: 65,
    operation: "*",
    answer: 4225,
  },
  {
    firstTerm: 5,
    secondTerm: 280,
    operation: "%->",
    answer: 14,
  },
  {
    firstTerm: 17,
    secondTerm: 3,
    operation: "*",
    answer: 51,
  },
  {
    firstTerm: 109,
    secondTerm: 109,
    operation: "*",
    answer: 11881,
  },
  {
    firstTerm: 1000,
    secondTerm: 5,
    operation: "-",
    answer: 995,
  },
  {
    firstTerm: 21,
    secondTerm: 21,
    operation: "*",
    answer: 441,
  },
  {
    firstTerm: 14,
    secondTerm: 500,
    operation: "*",
    answer: 7000,
  },
  {
    firstTerm: 25,
    secondTerm: 80,
    operation: "%->",
    answer: 20,
  },
  {
    firstTerm: 120,
    secondTerm: 20,
    operation: "/",
    answer: 6,
  },
  {
    firstTerm: 21,
    secondTerm: 21,
    operation: "*",
    answer: 21,
  },
  {
    firstTerm: 14,
    secondTerm: 13,
    operation: "*",
    answer: 182,
  },
  {
    firstTerm: 10,
    secondTerm: 2,
    operation: "/",
    answer: 5,
  },
  {
    firstTerm: 132,
    secondTerm: 99,
    operation: "-",
    answer: 33,
  },
  {
    firstTerm: 53,
    secondTerm: 53,
    operation: "*",
    answer: 2809,
  },
  {
    firstTerm: 19,
    secondTerm: 18,
    operation: "*",
    answer: 342,
  },
  {
    firstTerm: 25,
    secondTerm: 84,
    operation: "%->",
    answer: 21,
  },
  {
    firstTerm: 5,
    secondTerm: 15,
    operation: "*",
    answer: 75,
  },
  {
    firstTerm: 13,
    secondTerm: 11,
    operation: "*",
    answer: 143,
  },
  {
    firstTerm: 27,
    secondTerm: 11,
    operation: "*",
    answer: 297,
  },
  {
    firstTerm: 10,
    secondTerm: 10,
    operation: "*",
    answer: 100,
  },
  {
    firstTerm: 31,
    secondTerm: 9,
    operation: "-",
    answer: 22,
  },
  {
    firstTerm: 18,
    secondTerm: 19,
    operation: "*",
    answer: 342,
  },
  {
    firstTerm: 750,
    secondTerm: 50,
    operation: "/",
    answer: 15,
  },
  {
    firstTerm: 19,
    secondTerm: 4,
    operation: "*",
    answer: 76,
  },
  {
    firstTerm: 115,
    secondTerm: 115,
    operation: "*",
    answer: 13225,
  },
  {
    firstTerm: 50,
    secondTerm: 76,
    operation: "%->",
    answer: 38,
  },
  {
    firstTerm: 40,
    secondTerm: 5,
    operation: "*",
    answer: 200,
  },
  {
    firstTerm: 24,
    secondTerm: 9,
    operation: "*",
    answer: 216,
  },
  {
    firstTerm: 3,
    secondTerm: 7,
    operation: "*",
    answer: 21,
  },
  {
    firstTerm: 58,
    secondTerm: 58,
    operation: "*",
    answer: 3364,
  },
  {
    firstTerm: 2,
    secondTerm: 1650,
    operation: "%->",
    answer: 33,
  },
  {
    firstTerm: 42,
    secondTerm: 42,
    operation: "*",
    answer: 1764,
  },
  {
    firstTerm: 3,
    secondTerm: 8,
    operation: "*",
    answer: 24,
  },
  {
    firstTerm: 500,
    secondTerm: 37,
    operation: "%->",
    answer: 185,
  },
  {
    firstTerm: 14,
    secondTerm: 14,
    operation: "*",
    answer: 196,
  },
  {
    firstTerm: 49,
    secondTerm: 49,
    operation: "*",
    answer: 2401,
  },
  {
    firstTerm: 50,
    secondTerm: 3,
    operation: "*",
    answer: 150,
  },
  {
    firstTerm: 16,
    secondTerm: 99,
    operation: "*",
    answer: 1584,
  },
  {
    firstTerm: 15,
    secondTerm: 15,
    operation: "*",
    answer: 225,
  },
  {
    firstTerm: 14,
    secondTerm: 11,
    operation: "*",
    answer: 154,
  },
  {
    firstTerm: 105,
    secondTerm: 105,
    operation: "*",
    answer: 11025,
  },
  {
    firstTerm: 13,
    secondTerm: 9,
    operation: "*",
    answer: 117,
  },
  {
    firstTerm: 75,
    secondTerm: 25,
    operation: "/",
    answer: 3,
  },
  {
    firstTerm: 21,
    secondTerm: 11,
    operation: "*",
    answer: 231,
  },
  {
    firstTerm: 1,
    secondTerm: 1,
    operation: "*",
    answer: 1,
  },
  {
    firstTerm: 15,
    secondTerm: 4,
    operation: "-",
    answer: 11,
  },
  {
    firstTerm: 8,
    secondTerm: 8,
    operation: "*",
    answer: 64,
  },
  {
    firstTerm: 17,
    secondTerm: 19,
    operation: "*",
    answer: 323,
  },
  {
    firstTerm: 13,
    secondTerm: 13,
    operation: "*",
    answer: 169,
  },
  {
    firstTerm: 17,
    secondTerm: 4,
    operation: "*",
    answer: 68,
  },
  {
    firstTerm: 15,
    secondTerm: 8,
    operation: "*",
    answer: 120,
  },
  {
    firstTerm: 2,
    secondTerm: 6,
    operation: "*",
    answer: 12,
  },
  {
    firstTerm: 42,
    secondTerm: 48,
    operation: "*",
    answer: 2016,
  },
  {
    firstTerm: 15,
    secondTerm: 460,
    operation: "%->",
    answer: 69,
  },
  {
    firstTerm: 7,
    secondTerm: 7,
    operation: "*",
    answer: 49,
  },
  {
    firstTerm: 41,
    secondTerm: 21,
    operation: "*",
    answer: 861,
  },
  {
    firstTerm: 15,
    secondTerm: 420,
    operation: "%->",
    answer: 63,
  },
  {
    firstTerm: 500,
    secondTerm: 27,
    operation: "%->",
    answer: 135,
  },
  {
    firstTerm: 250,
    secondTerm: 26,
    operation: "%->",
    answer: 65,
  },
  {
    firstTerm: 14,
    secondTerm: 99,
    operation: "*",
    answer: 1386,
  },
  {
    firstTerm: 30,
    secondTerm: 50,
    operation: "*",
    answer: 1500,
  },
  {
    firstTerm: 243,
    secondTerm: 102,
    operation: "-",
    answer: 141,
  },
  {
    firstTerm: 20,
    secondTerm: 110,
    operation: "%->",
    answer: 22,
  },
  {
    firstTerm: 5,
    secondTerm: 440,
    operation: "%->",
    answer: 22,
  },
  {
    firstTerm: 5,
    secondTerm: 540,
    operation: "%->",
    answer: 27,
  },
  {
    firstTerm: 31,
    secondTerm: 3,
    operation: "*",
    answer: 93,
  },
  {
    firstTerm: 47,
    secondTerm: 20,
    operation: "*",
    answer: 940,
  },
  {
    firstTerm: 28,
    secondTerm: 25,
    operation: "*",
    answer: 700,
  },
  {
    firstTerm: 20,
    secondTerm: 165,
    operation: "%->",
    answer: 33,
  },
  {
    firstTerm: 47,
    secondTerm: 50,
    operation: "*",
    answer: 2350,
  },
  {
    firstTerm: 200,
    secondTerm: 38,
    operation: "%->",
    answer: 76,
  },
  {
    firstTerm: 49,
    secondTerm: 3,
    operation: "*",
    answer: 147,
  },
  {
    firstTerm: 1950,
    secondTerm: 50,
    operation: "/",
    answer: 39,
  },
  {
    firstTerm: 32,
    secondTerm: 19,
    operation: "*",
    answer: 608,
  },
  {
    firstTerm: 15,
    secondTerm: 20,
    operation: "%->",
    answer: 3,
  },
  {
    firstTerm: 6,
    secondTerm: 12,
    operation: "*",
    answer: 72,
  },
  {
    firstTerm: 14,
    secondTerm: 12,
    operation: "*",
    answer: 168,
  },
  {
    firstTerm: 50,
    secondTerm: 99,
    operation: "+",
    answer: 149,
  },
  {
    firstTerm: 29,
    secondTerm: 20,
    operation: "*",
    answer: 580,
  },
  {
    firstTerm: 12,
    secondTerm: 11,
    operation: "*",
    answer: 132,
  },
  {
    firstTerm: 43,
    secondTerm: 43,
    operation: "*",
    answer: 1849,
  },
  {
    firstTerm: 100,
    secondTerm: 25,
    operation: "/",
    answer: 4,
  },
  {
    firstTerm: 28,
    secondTerm: 2,
    operation: "/",
    answer: 14,
  },
  {
    firstTerm: 169,
    secondTerm: 91,
    operation: "-",
    answer: 78,
  },
  {
    firstTerm: 19,
    secondTerm: 18,
    operation: "*",
    answer: 342,
  },
  {
    firstTerm: 109,
    secondTerm: 109,
    operation: "*",
    answer: 11881,
  },
  {
    firstTerm: 50,
    secondTerm: 60,
    operation: "%->",
    answer: 30,
  },
  {
    firstTerm: 20,
    secondTerm: 20,
    operation: "*",
    answer: 400,
  },
  {
    firstTerm: 50,
    secondTerm: 50,
    operation: "*",
    answer: 2500,
  },
];
